// frontend/src/views/RequestDetails.vue
<template>
  <div>
    <button v-on:click="$router.go(-1)">← Back</button>
    <section>
      <h2>Request details</h2>
      <dl>
        <dt>Client IP</dt>
        <dd>
          <code>{{ this.requestDetails.clientIP }}</code>
        </dd>
        <dt>Headers</dt>
        <dd class="code-block">
          <pre><code class="language-json">{{ this.requestDetails.headers }}</code></pre>
        </dd>
        <dt>Host</dt>
        <dd>
          <code>{{ this.requestDetails.host }}</code>
        </dd>
        <dt>Method</dt>
        <dd>
          <code>{{ this.requestDetails.method }}</code>
        </dd>
        <dt>Path</dt>
        <dd>
          <code>{{ this.requestDetails.path }}</code>
        </dd>
        <dt>Referrer</dt>
        <dd>
          <code>{{ this.requestDetails.referrer }}</code>
        </dd>
        <dt>Time</dt>
        <dd>
          <code>{{ this.requestDetails.time }}</code>
        </dd>
        <dt>UID</dt>
        <dd>
          <code>{{ this.requestDetails.uid }}</code>
        </dd>
        <dt>URL</dt>
        <dd>
          <code>{{ this.requestDetails.url }}</code>
        </dd>
        <dt>User Agent</dt>
        <dd>
          <code>{{ this.requestDetails.userAgent }}</code>
        </dd>
        <dt>Body</dt>
        <dd>
          <pre><code>{{ this.requestDetails.body }}</code></pre>
        </dd>
      </dl>

      <h1>Response details</h1>
      <dl>
        <dt>Client IP</dt>
        <dd>
          <code>{{ this.responseDetails.clientIP }}</code>
        </dd>
        <dt>Headers</dt>
        <dd class="code-block">
          <pre><code class="language-json">{{ this.responseDetails.headers }}</code></pre>
        </dd>
        <dt>Path</dt>
        <dd>
          <code>{{ this.responseDetails.path }}</code>
        </dd>
        <dt>Size</dt>
        <dd>
          <code>{{ this.responseDetails.size }}</code>
        </dd>
        <dt>Status</dt>
        <dd>
          <code>{{ this.responseDetails.status }}</code>
        </dd>
        <dt>Time</dt>
        <dd>
          <code>{{ this.responseDetails.time }}</code>
        </dd>
        <dt>RequestUID</dt>
        <dd>
          <code>{{ this.responseDetails.requestUID }}</code>
        </dd>
        <dt>UID</dt>
        <dd>
          <code>{{ this.responseDetails.uid }}</code>
        </dd>
        <dt>Body</dt>
        <dd class="code-block">
          <pre><code class="language-json">{{ this.responseDetails.body }}</code></pre>
        </dd>
      </dl>
    </section>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { PropType } from "vue";
import { DetailedRequest, DetailedResponse } from "@/interfaces/requests";
import { RequestService } from "@/api/requests";

@Component({
  props: {
    requestUUID: String as PropType<string>
  }
})
export default class RequestDetails extends Vue {
  private requestDetails: DetailedRequest = {
    body: "",
    clientIP: "",
    headers: "",
    host: "",
    method: "",
    path: "",
    referrer: "",
    time: 0,
    uid: "",
    url: "",
    userAgent: ""
  };
  private responseDetails: DetailedResponse = {
    body: "",
    clientIP: "",
    headers: "",
    path: "",
    size: 0,
    status: "",
    time: 0,
    requestUID: "",
    uid: ""
  };

  async mounted(): Promise<void> {
    const requestedData = await RequestService.getRequest(
      this.$route.params.id
    );
    this.requestDetails = requestedData.data.request;
    this.responseDetails = requestedData.data.response;
  }
}
</script>

// static/goscope/src/app/request/request-details/request-details.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {Location} from '@angular/common';
import {RequestService} from "../request.service";
import {DetailedRequest, DetailedResponse} from "../requests";
import 'highlight.js/styles/dark.css';

@Component({
  selector: 'request-request-details',
  templateUrl: './request-details.component.html',
  styleUrls: ['./request-details.component.scss']
})
export class RequestDetailsComponent implements OnInit {
  requestDetails: DetailedRequest
  responseDetails: DetailedResponse

  constructor(
    private route: ActivatedRoute,
    private requestService: RequestService,
    private location: Location
  ) {

  }

  ngOnInit(): void {
    this.getRequest();
  }


  getRequest(): void {
    const id = this.route.snapshot.paramMap.get('id');
    this.requestService.getRequest(id)
      .subscribe(request => {
        this.requestDetails = request.data.request
        this.responseDetails = request.data.response
      });
  }

  goBack(): void {
    this.location.back();
  }

}

<div class="container p-3 m-3">
  <span class="cursor-pointer" (click)="goBack()">← Back</span><br/>
  <h2>Request details</h2>

  <p>Client IP</p>
  <pre><code [highlight]>{{requestDetails.clientIP}}</code></pre>
  <p>Headers</p>
  <pre><code [highlight]>{{requestDetails.headers}}</code></pre>
  <p>Host</p>
  <pre><code [highlight]>{{requestDetails.host}}</code></pre>
  <p>Method</p>
  <pre><code [highlight]>{{requestDetails.method}}</code></pre>
  <p>Path</p>
  <pre><code [highlight]>{{requestDetails.path}}</code></pre>
  <p>Referrer</p>
  <pre><code [highlight]>{{requestDetails.referrer}}</code></pre>
  <p>Time</p>
  <pre><code [highlight]>{{requestDetails.time}}</code></pre>
  <p>UID</p>
  <pre><code [highlight]>{{requestDetails.uid}}</code></pre>
  <p>URL</p>
  <pre><code [highlight]>{{requestDetails.url}}</code></pre>
  <p>User Agent</p>
  <pre><code [highlight]>{{requestDetails.userAgent}}</code></pre>
  <p>Body</p>
  <pre><code [highlight]>{{requestDetails.body}}</code></pre>
</div>

<div class="container p-3 m-3">
  <h2>Response details</h2>
  <p>Client IP</p>
  <pre><code [highlight]>{{responseDetails.clientIP}}</code></pre>
  <p>Headers</p>
  <pre><code [highlight]>{{responseDetails.headers}}</code></pre>
  <p>Path</p>
  <pre><code [highlight]>{{responseDetails.path}}</code></pre>
  <p>Size</p>
  <pre><code [highlight]>{{responseDetails.size}}</code></pre>
  <p>Status</p>
  <pre><code [highlight]>{{responseDetails.status}}</code></pre>
  <p>Time</p>
  <pre><code [highlight]>{{responseDetails.time}}</code></pre>
  <p>RequestUID</p>
  <pre><code [highlight]>{{responseDetails.requestUID}}</code></pre>
  <p>UID</p>
  <pre><code [highlight]>{{responseDetails.uid}}</code></pre>
  <p>Body</p>
  <pre><code [highlight]>{{responseDetails.body}}</code></pre>
</div>
