// frontend/src/views/RequestDetails.vue
<template>
  <div>
    <button v-on:click="$router.go(-1)">← Back</button>
    <section>
      <h2>Request details</h2>
      <dl>
        <dt>Client IP</dt>
        <dd>
          <code>{{ this.requestDetails.clientIP }}</code>
        </dd>
        <dt>Headers</dt>
        <dd class="code-block">
          <code class="language-json">{{ this.requestDetails.headers }}</code>
        </dd>
        <dt>Host</dt>
        <dd>
          <code>{{ this.requestDetails.host }}</code>
        </dd>
        <dt>Method</dt>
        <dd>
          <code>{{ this.requestDetails.method }}</code>
        </dd>
        <dt>Path</dt>
        <dd>
          <code>{{ this.requestDetails.path }}</code>
        </dd>
        <dt>Referrer</dt>
        <dd>
          <code>{{ this.requestDetails.referrer }}</code>
        </dd>
        <dt>Time</dt>
        <dd>
          <code>{{ this.requestDetails.time }}</code>
        </dd>
        <dt>UID</dt>
        <dd>
          <code>{{ this.requestDetails.uid }}</code>
        </dd>
        <dt>URL</dt>
        <dd>
          <code>{{ this.requestDetails.url }}</code>
        </dd>
        <dt>User Agent</dt>
        <dd>
          <code>{{ this.requestDetails.userAgent }}</code>
        </dd>
        <dt>Body</dt>
        <dd>
          <code>{{ this.requestDetails.body }}</code>
        </dd>
      </dl>

      <h1>Response details</h1>
      <dl>
        <dt>Client IP</dt>
        <dd>
          <code>{{ this.responseDetails.clientIP }}</code>
        </dd>
        <dt>Headers</dt>
        <dd class="code-block">
          <code class="language-json">{{ this.responseDetails.headers }}</code>
        </dd>
        <dt>Path</dt>
        <dd>
          <code>{{ this.responseDetails.path }}</code>
        </dd>
        <dt>Size</dt>
        <dd>
          <code>{{ this.responseDetails.size }}</code>
        </dd>
        <dt>Status</dt>
        <dd>
          <code>{{ this.responseDetails.status }}</code>
        </dd>
        <dt>Time</dt>
        <dd>
          <code>{{ this.responseDetails.time }}</code>
        </dd>
        <dt>RequestUID</dt>
        <dd>
          <code>{{ this.responseDetails.requestUID }}</code>
        </dd>
        <dt>UID</dt>
        <dd>
          <code>{{ this.responseDetails.uid }}</code>
        </dd>
        <dt>Body</dt>
        <dd class="code-block">
          <code class="language-json">{{ this.responseDetails.body }}</code>
        </dd>
      </dl>
    </section>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { PropType } from "vue";
import { DetailedRequest, DetailedResponse } from "@/interfaces/requests";
import { RequestService } from "@/api/requests";

@Component({
  props: {
    requestUUID: String as PropType<string>
  }
})
export default class RequestDetails extends Vue {
  private requestDetails: DetailedRequest = {
    body: "",
    clientIP: "",
    headers: "",
    host: "",
    method: "",
    path: "",
    referrer: "",
    time: 0,
    uid: "",
    url: "",
    userAgent: ""
  };
  private responseDetails: DetailedResponse = {
    body: "",
    clientIP: "",
    headers: "",
    path: "",
    size: 0,
    status: "",
    time: 0,
    requestUID: "",
    uid: ""
  };

  async mounted(): Promise<void> {
    const requestedData = await RequestService.getRequest(
      this.$route.params.id
    );
    this.requestDetails = requestedData.data.request;
    this.responseDetails = requestedData.data.response;
  }
}
</script>

// frontend/src/app/request/request-details/request-details.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {Location} from '@angular/common';
import {RequestService} from '../request.service';
import {DetailedRequest, DetailedResponse} from '../requests';
import {HighlightService} from "../../highlight.service";

@Component({
  selector: 'app-request-details',
  templateUrl: './request-details.component.html',
  styleUrls: ['./request-details.component.scss']
})
export class RequestDetailsComponent implements OnInit {
  requestDetails: DetailedRequest;
  responseDetails: DetailedResponse;

  constructor(
    private route: ActivatedRoute,
    private requestService: RequestService,
    private location: Location,
    private highlightService: HighlightService,
  ) {

  }

  ngAfterViewChecked() {
    this.highlightService.highlightAll();
  }

  ngOnInit(): void {
    this.getRequest();
  }


  getRequest(): void {
    const id = this.route.snapshot.paramMap.get('id');
    this.requestService.getRequest(id)
      .subscribe(request => {
        this.requestDetails = request.data.request;
        this.responseDetails = request.data.response;
      });
  }

  goBack(): void {
    this.location.back();
  }

}

<button class="cursor-pointer navbar-link" (click)="goBack()">← Back</button>

<section>
  <h2>Request details</h2>
  <dl>
    <dt>Client IP</dt>
    <dd><code >{{requestDetails.clientIP}}</code></dd>
    <dt>Headers</dt>
    <dd><code class="language-json">{{requestDetails.headers}}</code></dd>
    <dt>Host</dt>
    <dd><code >{{requestDetails.host}}</code></dd>
    <dt>Method</dt>
    <dd><code >{{requestDetails.method}}</code></dd>
    <dt>Path</dt>
    <dd><code >{{requestDetails.path}}</code></dd>
    <dt>Referrer</dt>
    <dd><code >{{requestDetails.referrer}}</code></dd>
    <dt>Time</dt>
    <dd><code >{{requestDetails.time}}</code></dd>
    <dt>UID</dt>
    <dd><code >{{requestDetails.uid}}</code></dd>
    <dt>URL</dt>
    <dd><code >{{requestDetails.url}}</code></dd>
    <dt>User Agent</dt>
    <dd><code >{{requestDetails.userAgent}}</code></dd>
    <dt>Body</dt>
    <dd><code >{{requestDetails.body}}</code></dd>
  </dl>

  <h1>Response details</h1>
  <dl>
    <dt>Client IP</dt>
    <dd><code >{{responseDetails.clientIP}}</code></dd>
    <dt>Headers</dt>
    <dd><code >{{responseDetails.headers}}</code></dd>
    <dt>Path</dt>
    <dd><code >{{responseDetails.path}}</code></dd>
    <dt>Size</dt>
    <dd><code >{{responseDetails.size}}</code></dd>
    <dt>Status</dt>
    <dd><code >{{responseDetails.status}}</code></dd>
    <dt>Time</dt>
    <dd><code >{{responseDetails.time}}</code></dd>
    <dt>RequestUID</dt>
    <dd><code >{{responseDetails.requestUID}}</code></dd>
    <dt>UID</dt>
    <dd><code >{{responseDetails.uid}}</code></dd>
    <dt>Body</dt>
    <dd><code >{{responseDetails.body}}</code></dd>
  </dl>
</section>
