// frontend/src/views/LogDetails.vue
<template>
  <div>
    <button v-on:click="$router.go(-1)">← Back</button>
    <section>
      <h2>Log details</h2>
      <dl>
        <dt>Message</dt>
        <dd>
          <code>{{ this.logDetails.data.logDetails.error }}</code>
        </dd>
        <dt>Time</dt>
        <dd>
          <code>{{ this.logDetails.data.logDetails.time }}</code>
        </dd>
      </dl>
    </section>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { DetailedLogsReponse } from "@/interfaces/logs";
import { LogService } from "@/api/logs";
import { PropType } from "vue";

@Component({
  props: {
    logUUID: String as PropType<string>
  }
})
export default class LogDetails extends Vue {
  private logDetails: DetailedLogsReponse = {
    data: {
      logDetails: {
        error: "",
        time: 0,
        uid: ""
      }
    },
    applicationName: ""
  };

  async mounted(): Promise<void> {
    this.logDetails = await LogService.getLog(this.$route.params.id);
  }
}
</script>

// frontend/src/app/log/log-details/log-details.component.ts
import {Component, OnInit} from '@angular/core';
import {DetailedLogsReponse} from '../logRecord';
import {ActivatedRoute} from '@angular/router';
import {Location} from '@angular/common';
import {LogService} from '../log.service';
import 'highlight.js/styles/dark.css';

@Component({
  selector: 'app-log-details',
  templateUrl: './log-details.component.html',
  styleUrls: ['./log-details.component.scss']
})

export class LogDetailsComponent implements OnInit {
  logDetails: DetailedLogsReponse;

  constructor(
    private route: ActivatedRoute,
    private logService: LogService,
    private location: Location
  ) {
  }

  ngOnInit(): void {
    this.getLog();
  }

  getLog(): void {
    const id = this.route.snapshot.paramMap.get('id');
    this.logService.getLog(id)
      .subscribe(log => {
        this.logDetails = log;
      });
  }

  goBack(): void {
    this.location.back();
  }

}

<button (click)="goBack()">← Back</button>
<section>
  <h2>Log details</h2>
  <dl>
    <dt>Message</dt>
    <dd><code [highlight]>{{logDetails.data.logDetails.error}}</code></dd>
    <dt>Time</dt>
    <dd><code [highlight]>{{logDetails.data.logDetails.time}}</code></dd>
  </dl>
</section>
