// static/goscope/src/app/request/request-list/request-list.component.ts
import {Component, OnInit} from '@angular/core';
import {RequestService} from "../request.service";
import {Requests} from "../requests";
import {intervalToLevels} from "../../time-utils";

@Component({
  selector: 'request-request-list',
  templateUrl: './request-list.component.html',
  styleUrls: ['./request-list.component.scss']
})
export class RequestListComponent implements OnInit {
  requests: Requests[]
  now: number

  constructor(private requestService: RequestService) {
  }

  ngOnInit(): void {
    this.now = Math.round(new Date().getTime() / 1000)
    this.getRequests()
  }

  getRequests(): void {
    this.requestService.getRequests().subscribe(requests => this.requests = requests.data);
  }

  timeDiffToHuman(value: number): string {
    return intervalToLevels(value)
  }

  applyMethodColor(method: string): string {
    if (method === 'GET') {
      return `<span class="badge-secondary">${method}</span>`
    } else if (method === 'POST') {
      return `<span class="badge-info">${method}</span>`
    } else if (method === 'PUT') {
      return `<span class="badge-info">${method}</span>`
    } else if (method === 'PATCH') {
      return `<span class="badge-turq">${method}</span>`
    } else if (method === 'DELETE') {
      return `<span class="badge-danger">${method}</span>`
    }
    return `<span class="badge-secondary">${method}</span>`
  }

  applyStatusColor(status: number): string {
    if (status >= 200 && status < 300) {
      return `<span class="badge-success">${status}</span>`
    } else if (status >= 300 && status < 400) {
      return `<span class="badge-info">${status}</span>`
    } else if (status >= 400 && status < 500) {
      return `<span class="badge-warning">${status}</span>`
    }
    return `<span class="badge-danger">${status}</span>`
  }

}

<table class="goscope-entries-table p-2">
  <tr>
    <th class="custom-td">Status</th>
    <th class="custom-td">Verb</th>
    <th class="custom-td text-center">Path</th>
    <th class="custom-td">Happened</th>
    <th class="custom-td"></th>
  </tr>

  <tr *ngFor="let request of requests" class="text-center">
    <td class="p-3 custom-td" [innerHTML]="applyStatusColor(request.responseStatus)"></td>
    <td class="monospaced p-3 custom-td" [innerHTML]="applyMethodColor(request.method)"></td>
    <td class="p-3 custom-td">{{request.path}}</td>
    <td class="p-3 custom-td">{{timeDiffToHuman(this.now - request.time)}} ago</td>
    <td class="p-3 custom-td">
      <a routerLink="/requests/{{request.uid}}" class="cursor-pointer">
        <svg class="eye-image" style="width:1.2em;height:1.2em;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 16">
          <path d="M16.56 13.66a8 8 0 0 1-11.32 0L.3 8.7a1 1 0 0 1 0-1.42l4.95-4.95a8 8 0 0 1 11.32 0l4.95 4.95a1 1 0 0 1 0 1.42l-4.95 4.95-.01.01zm-9.9-1.42a6 6 0 0 0 8.48 0L19.38 8l-4.24-4.24a6 6 0 0 0-8.48 0L2.4 8l4.25 4.24h.01zM10.9 12a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0-2a2 2 0 1 0 0-4 2 2 0 0 0 0 4z">
          </path>
        </svg>
      </a>
    </td>
  </tr>
</table>

// frontend/src/views/RequestList.vue
<template>
  <section>
    <table>
      <thead>
        <tr>
          <th>Status</th>
          <th>Verb</th>
          <th>Path</th>
          <th>Happened</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr :key="index" v-for="(request, index) in requests.data">
          <td v-html="applyStatusColor(request.responseStatus)"></td>
          <td v-html="applyMethodColor(request.method)"></td>
          <td>{{ request.path }}</td>
          <td>{{ timeDiffToHuman(now - request.time) }} ago</td>
          <td>
            <font-awesome-icon icon="eye" />
          </td>
        </tr>
      </tbody>
    </table>
    <nav class="text-center">
      <button v-on:click="previousPage()">← prev</button>
      <button v-on:click="nextPage()">next →</button>
    </nav>
  </section>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { intervalToLevels } from "@/utils/time";
import { RequestsEndpointResponse } from "@/interfaces/requests";
import { RequestService } from "@/api/requests";

@Component
export default class RequestList extends Vue {
  private requests: RequestsEndpointResponse = {
    data: [],
    applicationName: ""
  };

  private now: number = Math.round(new Date().getTime() / 1000);

  async mounted(): Promise<void> {
    this.requests = await RequestService.getRequests(1);
  }

  timeDiffToHuman(value: number): string {
    return intervalToLevels(value);
  }

  applyMethodColor(method: string): string {
    if (method === "GET") {
      return `<span class="badge-secondary">${method}</span>`;
    } else if (method === "POST") {
      return `<span class="badge-info">${method}</span>`;
    } else if (method === "PUT") {
      return `<span class="badge-info">${method}</span>`;
    } else if (method === "PATCH") {
      return `<span class="badge-turq">${method}</span>`;
    } else if (method === "DELETE") {
      return `<span class="badge-danger">${method}</span>`;
    }
    return `<span class="badge-secondary">${method}</span>`;
  }

  applyStatusColor(status: number): string {
    if (status >= 200 && status < 300) {
      return `<span class="badge-success">${status}</span>`;
    } else if (status >= 300 && status < 400) {
      return `<span class="badge-info">${status}</span>`;
    } else if (status >= 400 && status < 500) {
      return `<span class="badge-warning">${status}</span>`;
    }
    return `<span class="badge-danger">${status}</span>`;
  }
}
</script>
